[package]
name = "colorable-rs"
version = "0.1.0"
authors = ["statiolake <statiolake@gmail.com>"]
edition = "2018"

[target."cfg(windows)".dependencies]
kernel32-sys = "0.2.2"
winapi = { version = "0.3.6", features = ["minwindef", "winbase", "wincon", "winnt", "processenv"] }

[dependencies]
